/*
 * generated by Xtext
 */
package org.mgs.graphics.pm.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class PmDslScopeProvider extends AbstractDeclarativeScopeProvider {

//	IScope scope_ModuleCall_args(ModuleCall ctx, EReference ref){
//		return getScope(ctx.getModule(), ref);
//	}
//
//	IScope scope_ModuleCall_output(ModuleCall ctx, EReference ref){
//		return getScope(ctx.getModule(), ref);
//	}
	
}
