/*
* generated by Xtext
*/
package org.mgs.graphics.pm.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class PmDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
