/*
* generated by Xtext
*/
package org.mgs.graphics.pm.ui.contentassist;

import org.mgs.graphics.pm.ui.contentassist.AbstractPmDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PmDslProposalProvider extends AbstractPmDslProposalProvider {

}
