
/*
 * generated by Xtext
 */
 
package org.mgs.graphics.pm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class PmDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.mgs.graphics.pm.ui.internal.PmDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.mgs.graphics.pm.ui.internal.PmDslActivator.getInstance().getInjector("org.mgs.graphics.pm.PmDsl");
	}
	
}
