/*
 * generated by Xtext
 */
package org.mgs.graphics.pm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PmDslRuntimeModule extends org.mgs.graphics.pm.AbstractPmDslRuntimeModule {

}
