/*
* generated by Xtext
*/
package org.mgs.graphics.pm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PmDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/mgs/graphics/pm/parser/antlr/internal/InternalPmDsl.tokens");
	}
}
