/*
 * generated by Xtext
 */
package org.mgs.graphics.pm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PmDslUiModule extends org.mgs.graphics.pm.ui.AbstractPmDslUiModule {
	public PmDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
